version: "3.8"

services:
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:latest
    networks:
      - main
    ports:
      - "5672:5672"
    restart: on-failure

  postgres:
    hostname: postgres
    image: postgres:latest
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - main
    restart: on-failure
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile.django_snakemake
    command:  sh -c "python manage.py makemigrations blast_project
     && python manage.py migrate blast_project
      && python manage.py makemigrations one_way_blast
      && python manage.py migrate one_way_blast
      && python manage.py makemigrations external_tools
      && python manage.py migrate external_tools
     && python manage.py runserver 0.0.0.0:8080"
    networks:
      - main
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - postgres
    image: blast_celery_snakemake_app
    volumes:
      - ./data:/blast/reciprocal_blast/media
      - ./tmp:/blast/reciprocal_blast/tmp
      - ./celery_blast:/blast/reciprocal_blast
    ports:
      - "8080:8080"

  celery_worker:
    command: sh -c "./wait-for rabbitmq:5672 && ./wait-for web:8080 -- celery -A celery_blast worker -l info"
    depends_on:
      - web
      - postgres
      - rabbitmq
    image: blast_celery_snakemake_app
    networks:
      - main
    restart: unless-stopped

  panoptes:
    command: sh -c "./wait-for web:8080 -- panoptes"
    depends_on:
      - web
      - postgres
      - rabbitmq
    image: blast_celery_snakemake_app
    ports:
      - "5000:5000"
    networks:
      - main
    restart: unless-stopped

  flower:
    command: sh -c "./wait-for rabbitmq:5672 && ./wait-for web:8080 -- flower -A celery_blast --port=5555"
    networks:
      - main
    environment:
      AMQP_HOST: 'rabbitmq.local'
      AMQP_ADMIN_HOST: 'rabbitmq.local'
    image: blast_celery_snakemake_app
    depends_on:
      - web
      - postgres
      - rabbitmq
    ports:
      - "5555:5555"
    restart: unless-stopped

  tools:
    build:
      context: .
      dockerfile: Dockerfile.bioinformatic_tools
    networks:
      - main
    ports:
      - "5001:5001"
    restart: unless-stopped
    volumes:
      - ./flask_api_bioinformatic_tools:/application
      - ./data:/application/data
networks:
  main:
