# Generated by Django 4.2.10 on 2026-07-15 12:31

from django.db import migrations, models


STATUS_TO_LIFECYCLE = {
    'PENDING': 'QUEUED',
    'STARTED': 'RUNNING',
    'PROGRESS': 'RUNNING',
    'RETRY': 'RETRYING',
    'SUCCESS': 'SUCCESSFUL',
    'FAILURE': 'FAILED',
    'REVOKED': 'CANCELLED',
}


def backfill_workflow_lifecycle(apps, schema_editor):
    BlastProject = apps.get_model('blast_project', 'BlastProject')
    RemoteBlastProject = apps.get_model('blast_project', 'RemoteBlastProject')

    for project in BlastProject.objects.select_related('project_execution_snakemake_task'):
        task = project.project_execution_snakemake_task
        if task is None:
            continue
        project.project_workflow_state = STATUS_TO_LIFECYCLE.get(task.status, 'RUNNING')
        project.project_workflow_execution_token = task.task_id
        project.save(update_fields=['project_workflow_state', 'project_workflow_execution_token'])

    for project in RemoteBlastProject.objects.select_related('r_project_execution_snakemake_task'):
        task = project.r_project_execution_snakemake_task
        if task is None:
            continue
        project.r_project_workflow_state = STATUS_TO_LIFECYCLE.get(task.status, 'RUNNING')
        project.r_project_workflow_execution_token = task.task_id
        project.save(update_fields=['r_project_workflow_state', 'r_project_workflow_execution_token'])


def reset_workflow_lifecycle(apps, schema_editor):
    BlastProject = apps.get_model('blast_project', 'BlastProject')
    RemoteBlastProject = apps.get_model('blast_project', 'RemoteBlastProject')
    BlastProject.objects.update(project_workflow_state='STARTABLE', project_workflow_execution_token=None)
    RemoteBlastProject.objects.update(r_project_workflow_state='STARTABLE', r_project_workflow_execution_token=None)


class Migration(migrations.Migration):

    dependencies = [
        ('blast_project', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blastproject',
            name='project_workflow_execution_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='current reciprocal workflow execution token'),
        ),
        migrations.AddField(
            model_name='blastproject',
            name='project_workflow_state',
            field=models.CharField(choices=[('STARTABLE', 'Startable'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('RETRYING', 'Retrying'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='STARTABLE', max_length=20, verbose_name='reciprocal workflow lifecycle state'),
        ),
        migrations.AddField(
            model_name='remoteblastproject',
            name='r_project_workflow_execution_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='current remote reciprocal workflow execution token'),
        ),
        migrations.AddField(
            model_name='remoteblastproject',
            name='r_project_workflow_state',
            field=models.CharField(choices=[('STARTABLE', 'Startable'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('RETRYING', 'Retrying'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='STARTABLE', max_length=20, verbose_name='remote reciprocal workflow lifecycle state'),
        ),
        migrations.RunPython(backfill_workflow_lifecycle, reset_workflow_lifecycle),
    ]
