# Generated by Django 2.2.5 on 2021-06-02 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blast_project', '0002_auto_20210602_1013'),
        ('django_celery_results', '0008_chordcounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneWayBlastProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200, unique=True, verbose_name='title of this one way blast project')),
                ('project_query_sequences', models.CharField(max_length=200, verbose_name='query sequence filepath')),
                ('project_database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blast_project.BlastDatabase', verbose_name='associated BLAST database')),
                ('project_execution_task_result', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_results.TaskResult', verbose_name='django_celery_results taskresult model for this project')),
                ('project_settings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blast_project.BlastSettings', verbose_name='BLAST settings')),
                ('project_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user who created this project')),
            ],
        ),
    ]
