# Generated by Django 2.2.5 on 2021-06-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_way_blast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onewayblastproject',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
