"""
    Django settings for celery_blast project.

    Generated by 'django-admin startproject' using Django 2.2.5.

    For more information on this file, see
    https://docs.djangoproject.com/en/2.2/topics/settings/

    For the full list of settings and their values, see
    https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from decouple import config
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/


PLACEHOLDER_SECRET_TOKENS = (
    "change-me",
    "changeme",
    "placeholder",
    "not-for-production",
    "not-a-real",
    "invalid",
    "example",
    "django-insecure",
)

DEVELOPMENT_SECRET_DEFAULTS = {
    "password",
    "postgres",
    "secret",
    "secret-key",
    "user",
}


def _is_blank(value):
    return value is None or str(value).strip() == ""


def _is_placeholder_secret(value):
    if _is_blank(value):
        return True
    normalized = str(value).strip().lower()
    return (
        normalized in DEVELOPMENT_SECRET_DEFAULTS
        or any(token in normalized for token in PLACEHOLDER_SECRET_TOKENS)
    )


def _read_secret_setting(name, default=None, required=False):
    file_path = os.environ.get(f"{name}_FILE")
    if file_path and file_path.strip():
        try:
            with open(file_path, encoding="utf-8") as secret_file:
                value = secret_file.read().strip()
        except OSError as exc:
            raise ImproperlyConfigured(f"{name}_FILE could not be read") from exc
    else:
        value = config(name, default=default)

    if required and _is_blank(value):
        raise ImproperlyConfigured(f"{name} must be supplied")
    return value


def _is_production_environment(value):
    return str(value).strip().lower() in {"prod", "production"}


def _validate_production_configuration(
    *,
    cathi_env,
    debug,
    secret_key,
    sql_engine,
    sql_database,
    sql_user,
    sql_password,
    sql_host,
):
    if not _is_production_environment(cathi_env):
        return

    errors = []
    if debug:
        errors.append("DEBUG must be false")
    if _is_placeholder_secret(secret_key) or len(str(secret_key).strip()) < 32:
        errors.append("SECRET_KEY must be a strong runtime secret")
    if _is_placeholder_secret(sql_password):
        errors.append("SQL_PASSWORD must be a non-placeholder runtime secret")
    if _is_blank(sql_engine) or str(sql_engine).strip() == "django.db.backends.sqlite3":
        errors.append("SQL_ENGINE must not use the development sqlite backend")
    if _is_blank(sql_database) or os.path.basename(str(sql_database).strip()) == "db.sqlite3":
        errors.append("SQL_DATABASE must not use the development sqlite database")
    if _is_placeholder_secret(sql_user):
        errors.append("SQL_USER must not use a development default")
    if _is_blank(sql_host) or str(sql_host).strip().lower() in {"localhost", "127.0.0.1"}:
        errors.append("SQL_HOST must not use a local development host")

    if errors:
        raise ImproperlyConfigured(
            "Production secret configuration is invalid: " + "; ".join(errors)
        )


# SECURITY WARNING: keep the secret key used in production secret!
CATHI_ENV = config("CATHI_ENV", default="development")
SECRET_KEY = _read_secret_setting("SECRET_KEY", required=True)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = config('DJANGO_ALLOWED_HOSTS').split(" ")
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS').split(" ")

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'blast_project',
    'refseq_transactions',
    'django_celery_results',
    'celery_progress',
    'one_way_blast',
    'external_tools',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'celery_blast.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['celery_blast/templates', 'static/images/result_images', 'media/blast_projects', 'media/one_way_blast',
                 'media/one_way_blast/remote_searches', 'media'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'celery_blast.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

SQL_ENGINE = config('SQL_ENGINE', default="django.db.backends.sqlite3")
SQL_DATABASE = config('SQL_DATABASE', default=BASE_DIR+'/db.sqlite3')
SQL_USER = config('SQL_USER',default='user')
SQL_PASSWORD = _read_secret_setting('SQL_PASSWORD', default='password')
SQL_HOST = config('SQL_HOST',default='localhost')
SQL_PORT = config('SQL_PORT',default='5432')

DATABASES = {
    'default': {
        'ENGINE': SQL_ENGINE,#'django.db.backends.postgresql_psycopg2',
        'NAME': SQL_DATABASE,#'postgres',
        'USER': SQL_USER,#'postgres',
        'PASSWORD': SQL_PASSWORD,#'postgres',
        'HOST': SQL_HOST,#'postgres',
        'PORT': SQL_PORT#'5432',
    }
}

_validate_production_configuration(
    cathi_env=CATHI_ENV,
    debug=DEBUG,
    secret_key=SECRET_KEY,
    sql_engine=SQL_ENGINE,
    sql_database=SQL_DATABASE,
    sql_user=SQL_USER,
    sql_password=SQL_PASSWORD,
    sql_host=SQL_HOST,
)

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = '/blast/reciprocal_blast/assets'

MEDIA_URL = '/media/'
MEDIA_ROOT = '/media/'
PROTECTED_MEDIA_ROOT = config('PROTECTED_MEDIA_ROOT', default=os.path.join(BASE_DIR, 'media'))
PROTECTED_MEDIA_INTERNAL_URL = config('PROTECTED_MEDIA_INTERNAL_URL', default='/_protected_media/')
PROTECTED_MEDIA_USE_X_ACCEL = config('PROTECTED_MEDIA_USE_X_ACCEL', default=False, cast=bool)
PROTECTED_MEDIA_X_ACCEL_SIZE_THRESHOLD = config(
    'PROTECTED_MEDIA_X_ACCEL_SIZE_THRESHOLD',
    default=1048576,
    cast=int,
)

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)

FILE_UPLOAD_TEMP_DIR = '/tmp'

# celery settings from celery projects website and following github repo: https://github.com/chrisk314/django-celery-docker-example/tree/master/mysite/settings
CELERY_BROKER_URL = 'pyamqp://rabbitmq:5672'
CELERY_RESULT_BACKEND = 'django-db'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

CELERY_TASK_SOFT_TIME_LIMIT = 345600  # 2 * 60min = 120min * 60sec = 7200sec
CELERY_TASK_TIME_LIMIT = 345660
SUBPROCESS_TIME_LIMIT = CELERY_TASK_SOFT_TIME_LIMIT - 5
CELERY_TASK_ACKS_LATE = config('CELERY_TASK_ACKS_LATE', default=True, cast=bool)
CELERY_TASK_REJECT_ON_WORKER_LOST = config('CELERY_TASK_REJECT_ON_WORKER_LOST', default=True, cast=bool)
CELERY_WORKER_PREFETCH_MULTIPLIER = config('CELERY_WORKER_PREFETCH_MULTIPLIER', default=1, cast=int)
CELERY_TASK_DEFAULT_QUEUE = config('CELERY_INTERACTIVE_QUEUE', default='interactive')
CELERY_INTERACTIVE_QUEUE = config('CELERY_INTERACTIVE_QUEUE', default='interactive')
CELERY_WORKFLOW_QUEUE = config('CELERY_WORKFLOW_QUEUE', default='long_bio')
CELERY_MAINTENANCE_QUEUE = config('CELERY_MAINTENANCE_QUEUE', default='maintenance')
CELERY_TASK_ROUTES = {
    'blast_project.tasks.execute_reciprocal_blast_project': {'queue': CELERY_WORKFLOW_QUEUE},
    'blast_project.tasks.execute_remote_reciprocal_blast_project': {'queue': CELERY_WORKFLOW_QUEUE},
    'one_way_blast.tasks.execute_one_way_blast_project': {'queue': CELERY_WORKFLOW_QUEUE},
    'one_way_blast.tasks.execute_one_way_remote_blast_project': {'queue': CELERY_WORKFLOW_QUEUE},
    'external_tools.tasks.execute_multiple_sequence_alignment': {'queue': CELERY_WORKFLOW_QUEUE},
    'external_tools.tasks.execute_phylogenetic_tree_building': {'queue': CELERY_WORKFLOW_QUEUE},
    'external_tools.tasks.execute_multiple_sequence_alignment_for_all_query_sequences': {'queue': CELERY_WORKFLOW_QUEUE},
    'external_tools.tasks.execute_fasttree_phylobuild_for_all_query_sequences': {'queue': CELERY_WORKFLOW_QUEUE},
    'external_tools.tasks.cdd_domain_search_with_rbhs_task': {'queue': CELERY_WORKFLOW_QUEUE},
    'external_tools.tasks.execute_domain_multiple_sequence_alignment': {'queue': CELERY_WORKFLOW_QUEUE},
    'external_tools.tasks.execute_phylogenetic_tree_building_with_domains': {'queue': CELERY_WORKFLOW_QUEUE},
    'external_tools.tasks.synteny_calculation_task': {'queue': CELERY_WORKFLOW_QUEUE},
    'blast_project.tasks.execute_makeblastdb_with_uploaded_genomes': {'queue': CELERY_MAINTENANCE_QUEUE},
    'blast_project.tasks.download_and_format_taxdb': {'queue': CELERY_MAINTENANCE_QUEUE},
    'blast_project.tasks.download_and_decompress_cdd_database': {'queue': CELERY_MAINTENANCE_QUEUE},
    'blast_project.tasks.write_species_taxids_into_file': {'queue': CELERY_MAINTENANCE_QUEUE},
    'blast_project.tasks.calculate_database_statistics_task': {'queue': CELERY_MAINTENANCE_QUEUE},
    'external_tools.tasks.setup_cathi_download_cdd_refseq_genbank_assembly_files': {'queue': CELERY_MAINTENANCE_QUEUE},
    'external_tools.tasks.download_organism_protein_sequences_task': {'queue': CELERY_MAINTENANCE_QUEUE},
    'external_tools.tasks.download_entrez_search_associated_protein_sequences': {'queue': CELERY_MAINTENANCE_QUEUE},
    'external_tools.tasks.entrez_search_task': {'queue': CELERY_INTERACTIVE_QUEUE},
    'refseq_transactions.tasks.download_refseq_assembly_summary': {'queue': CELERY_MAINTENANCE_QUEUE},
    'refseq_transactions.tasks.write_alias_file': {'queue': CELERY_MAINTENANCE_QUEUE},
    'refseq_transactions.tasks.format_blast_databases': {'queue': CELERY_MAINTENANCE_QUEUE},
    'refseq_transactions.tasks.create_chunks_of_databases': {'queue': CELERY_MAINTENANCE_QUEUE},
    'refseq_transactions.tasks.download_wget_ftp_paths': {'queue': CELERY_MAINTENANCE_QUEUE},
    'refseq_transactions.tasks.download_blast_databases_based_on_summary_file': {'queue': CELERY_MAINTENANCE_QUEUE},
}

CATHI_WORKFLOW_JOB_CORES = config('CATHI_WORKFLOW_JOB_CORES', default=1, cast=int)
CATHI_MAX_BLAST_THREADS = config('CATHI_MAX_BLAST_THREADS', default=1, cast=int)
CATHI_MAX_NUM_ALIGNMENTS = config('CATHI_MAX_NUM_ALIGNMENTS', default=10000, cast=int)
CATHI_MAX_TARGET_SEQS = config('CATHI_MAX_TARGET_SEQS', default=10000, cast=int)
CATHI_MAX_HSPS = config('CATHI_MAX_HSPS', default=500, cast=int)
CATHI_MAX_RBHS_FOR_PHYLO = config('CATHI_MAX_RBHS_FOR_PHYLO', default=500, cast=int)
CATHI_MAX_ENTREZ_RECORDS = config('CATHI_MAX_ENTREZ_RECORDS', default=10000, cast=int)
CATHI_MAX_UPLOAD_BYTES = config('CATHI_MAX_UPLOAD_BYTES', default=100 * 1024 * 1024, cast=int)
CATHI_MAX_ACTIVE_WORKFLOWS_PER_USER = config('CATHI_MAX_ACTIVE_WORKFLOWS_PER_USER', default=1, cast=int)
CATHI_EFFECTIVE_BLAST_THREADS = max(1, min(CATHI_WORKFLOW_JOB_CORES, CATHI_MAX_BLAST_THREADS))

'''
# django setting.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'my_cache_table',
    }
}
'''
#CSRF_TRUSTED_ORIGINS = ['https://*','https://*.127.0.0.1','http://*','http://*.127.0.0.1']

DEFAULT_AUTO_FIELD=config('DEFAULT_AUTO_FIELD', default='django.db.models.AutoField')
DATA_UPLOAD_MAX_MEMORY_SIZE = config('DATA_UPLOAD_MAX_MEMORY_SIZE', default=CATHI_MAX_UPLOAD_BYTES, cast=int)
FILE_UPLOAD_MAX_MEMORY_SIZE = config('FILE_UPLOAD_MAX_MEMORY_SIZE', default=CATHI_MAX_UPLOAD_BYTES, cast=int)
CELERY_RESULT_EXTENDED = True
STATIC_RESULT_IMAGES = config('STATIC_RESULT_IMAGES')
BLAST_PROJECT_DIR = config('BLAST_PROJECT_DIR')
REMOTE_BLAST_PROJECT_DIR = config('REMOTE_BLAST_PROJECT_DIR')
ONE_WAY_BLAST_PROJECT_DIR = config('ONE_WAY_BLAST_PROJECT_DIR')
BLAST_DATABASE_DIR = config('BLAST_DATABASE_DIR')
CDD_DIR = config('CDD_DIR')
ESEARCH_OUTPUT = config('ESEARCH_OUTPUT')
CDD_DATABASE_URL = config("CDD_DATABASE_URL")
TAXDB_URL = config("TAXDB_URL")
REFSEQ_ASSEMBLY_FILE = config('REFSEQ_ASSEMBLY_FILE')
REFSEQ_URL = config("REFSEQ_URL")
GENBANK_ASSEMBLY_FILE = config("GENBANK_ASSEMBLY_FILE")
GENBANK_URL = config("GENBANK_URL")
TAXONOMIC_NODES = config('TAXONOMIC_NODES')
