configfile: "./snakefile_config"

rule all:
	input:
		"blast_results.table", "blast_results.html"

rule blast:
	input: queries=config['query_sequence']
	output: "blast_results.table"
	params: word_size=config['word_size'], e_value=config['e_value'], num_alignments=config['num_alignments'], num_threads=config['num_threads'], database=config['blastdb']
	shell:
		"blastp -db {params.database} -outfmt \"6 qseqid sseqid evalue bitscore qgi sgi sacc staxids sscinames scomnames stitle\" -out {output} -word_size {params.word_size} -evalue {params.e_value} -num_alignments {params.num_alignments} -num_threads {params.num_threads} -query {input.queries}"


rule blast_table_to_html:
	input: res="blast_results.table"
	output: html_table="blast_results.html"
	script:
		"../../../static/snakefiles/one_way_blast/blast_tables_to_html.py"
