configfile: "./snakefile_config"

rule all:
	input:
		"genus_bars.html"

rule blast:
	input: queries=config['query_sequence']
	output: "blast_results.table"
	params: word_size=config['word_size'], e_value=config['e_value'], num_alignments=config['num_alignments'], num_threads=config['num_threads'], database=config['blastdb']
	shell:
		"blastp -db {params.database} -outfmt \"6 qseqid sseqid evalue bitscore qgi sgi sacc staxids sscinames scomnames stitle\" -out {output} -word_size {params.word_size} -evalue {params.e_value} -num_alignments {params.num_alignments} -num_threads {params.num_threads} -query {input.queries}"

'''
rule blast_table_to_html:
	input: res="blast_results.table"
	output: html_table="blast_results.html"
	script:
		"../../../static/snakefiles/one_way_blast/blast_tables_to_html.py"
'''

rule blast_results_to_plots:
	input: blast_results="blast_results.table", query_file=config['query_sequence']
	params: genus_bars_static="../../../static/images/result_images/one_way_blast/" + str(config['project_id']) + '/genus_bars.html'
	output: genus_bars="genus_bars.html",html_table="blast_results.html"
	script:
		"../../../static/snakefiles/one_way_blast/plot_results.py"
